name: site-host

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    restart: always
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/ssl:/etc/nginx/ssl:ro
  rainfall-climate-atlas:
    build:
      context: .
      dockerfile: next.Dockerfile
    restart: always
    container_name: rainfall-climate-atlas
    ports:
      - "3000:3000"