import React from "react";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import L from "leaflet";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // var map = L.map("rainfall-interactive-map").setView([51.505, -0.09], 13);
  // L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
  //   maxZoom: 19,
  //   attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
  // }).addTo(map);
  return (
    <html lang="en">
      <head>
        <title>Hawaii Rainfall Atlas</title>
        {/* Required for Leaflet */}
        <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
              integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY="
              crossOrigin=""/>
        <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
                integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="
                crossOrigin=""></script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div>
          <div className="h-36">
            <img className="mx-auto" src="/rainfall_banner.png" alt="Rainfall banner" />
          </div>
          <nav className="flex justify-center space-x-4 font-bold text-white my-2">
            <div><Link href="/">Home</Link></div>
            <div><Link href="/interactive-map">Interactive Map</Link></div>
          </nav>
          <main className="min-h-screen">{children}</main>
          <footer className="flex row-start-3 justify-center">
            Footer
          </footer>
        </div>
      </body>
    </html>
  );
}
